#pragma config(Sensor, S2,     UltrassonicRight, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     UltrassonicLeft, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Esquerda,      , PIDControl, encoder)
#pragma config(Motor,  motorB,          Braco,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Direita,       tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

// Bibliotecas - Não existem bibliotecas para o RobotC

task main ()
{
	float  distancialeft, distanciaright;
	int jogada = 10;

	//////////////////////////////// SELEÇÃO DE JOGADA ////////////////////////////////
	while(jogada == 10)
	{
		if(getButtonPress(buttonEnter)==1)// Botão - Centro
		{
			jogada = 1;
			displayCenteredBigTextLine(4,"Centro");
		}
		eraseDisplay();
	}
	//////////////////////////////// FIM DA SELEÇÃO DE JOGADA ////////////////////////////////

	// Aguarda 5 segundos para o robô inciar a jogada
	displayCenteredBigTextLine(4,"PRONTO");
	delay(5000);
	eraseDisplay();

	// Responsável por fazer a arma acionar
	motor[motorB] = -100;
	delay(180);
	motor[motorB] =  0;

	// Responsável por fazer o robô realizar a jogada inicial antes de procurar o adversário
	motor[motorC] =  100;
	motor[motorA] =  100;
	delay(1000);

	// Loop infinito para o robô procurar o adversário
	for(;;)
	{
		// Leitura da distância dos sensores ultrassônicos
		distancialeft = 0;
  		distanciaright = 0;
		distanciaright = SensorValue[UltrassonicRight];
		distancialeft = SensorValue[UltrassonicLeft];

		// Caso o sensor da direita esteja mais próximo (ao robô adversário) do que o da esquerda
		if(distanciaright < distancialeft)
		{
			motor[motorC] = -100;
			motor[motorA] = 100;			
		}
		// Caso o sensor da esquerda esteja mais próximo (ao robô adversário) do que o da direita
		if(distanciaright > distancialeft)
		{
			motor[motorC] = 100;
			motor[motorA] = -100;			
		}
		// Caso os dois estejam lendo a mesma distância
		if(distanciaright = distancialeft)
		{
			motor[motorC] = 100;
			motor[motorA] = 100;			
		}

	}
}
